version: 0.2

env:
  variables:
    FIND_CERT_STAGING_URL: "https://find-energy-certificate-staging.centraldatastore.net"
    GET_CERT_STAGING_URL: "https://getting-new-energy-certificate-staging.centraldatastore.net"

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - make performance-test-staging
