version: 0.2

env:
  variables:
    FIND_CERT_STAGING_URL: "https://mhclg-epb-static-start-pages-staging.london.cloudapps.digital/find-an-energy-certificate.html"
    GET_CERT_STAGING_URL: "https://mhclg-epb-static-start-pages-staging.london.cloudapps.digital/getting-a-new-energy-certificate.html"

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - make performance-test-staging
